## masukan library yang digunakan ##

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to C:\Users\Sisca
[nltk_data]     Cahyani\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

## load datset ##

In [3]:
data = pd.read_csv('dataset_sms_spam_v1.csv')
data.head()

                                                teks  label
0  IM3 Ooredoo: isi ulang min 50rb hari ini dpt b...      2
1  TSEL-INFO: Paket Combo Sakti 75GB + nelpon sep...      2
2  XL Axiata khusus pelanggan setia bonus TikTok ...      2
3  Smartfren: internet unlimited nonstop mulai 40...      2
4  [PROMO] Beli paket Flash mulai 1GB di MY TELKO...      2

## Text Preprocessing ##

## Case Folding

In [4]:
import re

# membuat fungsi untuk case folding
def casefolding(text):
    text = text.lower()                                 # merubah kalimat jadi huruf kecil
    text = re.sub(r'https?://\S+|wwww\.\S+','', text)   # menghapus url dari kalimat
    text = re.sub(r'[-+]?[0-9]+', '', text)              # menghaps angka dari kalimat
    text = re.sub(r'[^\w\s]', '', text)                 # menghapus tanda baca
    text = text.strip()
    return text

In [5]:
# membandingkan before dan after case folding
raw_sample = data['teks'].iloc[2]
case_folding = casefolding(raw_sample)

print('Raw data\t : ',raw_sample)
print('Case Folding\t :', case_folding)

Raw data	 :  XL Axiata khusus pelanggan setia bonus TikTok unlimited 7 hari tanpa biaya tambahan. aktifkan via myXL sekarang
Case Folding	 : xl axiata khusus pelanggan setia bonus tiktok unlimited  hari tanpa biaya tambahan aktifkan via myxl sekarang

In [6]:
key_norm = pd.read_csv('key_norm.csv')

def text_normalize(text):
    text = ' '.join([key_norm[key_norm['singkat'] == word]['hasil'].values[0]
    if (key_norm['singkat'] == word).any()
    else word for word in text.split()                 
    ])

    text = str.lower(text)
    return text

In [7]:
# membandingkan before dan after word normalization

raw_data = data['teks'].iloc[696]
word_normal = text_normalize(raw_data)

print('Raw Data\t :', raw_data)
print('Word Normalize\t :', word_normal)

Raw Data	 : Belum de.. Saya lagi nyoba ngejar..
Word Normalize	 : belum de.. saya lagi nyoba ngejar..

## filtering (Stopword Removal)

In [8]:
from nltk.tokenize import sent_tokenize, word_tokenize
from nltk.corpus import stopwords

stopwords_ind = stopwords.words('indonesian')

In [9]:
len(stopwords_ind)

758

In [10]:
# melihat daftar stopwords dari nltk
stopwords_ind

['ada',
 'adalah',
 'adanya',
 'adapun',
 'agak',
 'agaknya',
 'agar',
 'akan',
 'akankah',
 'akhir',
 'akhiri',
 'akhirnya',
 'aku',
 'akulah',
 'amat',
 'amatlah',
 'anda',
 'andalah',
 'antar',
 'antara',
 'antaranya',
 'apa',
 'apaan',
 'apabila',
 'apakah',
 'apalagi',
 'apatah',
 'artinya',
 'asal',
 'asalkan',
 'atas',
 'atau',
 'ataukah',
 'ataupun',
 'awal',
 'awalnya',
 'bagai',
 'bagaikan',
 'bagaimana',
 'bagaimanakah',
 'bagaimanapun',
 'bagi',
 'bagian',
 'bahkan',
 'bahwa',
 'bahwasanya',
 'baik',
 'bakal',
 'bakalan',
 'balik',
 'banyak',
 'bapak',
 'baru',
 'bawah',
 'beberapa',
 'begini',
 'beginian',
 'beginikah',
 'beginilah',
 'begitu',
 'begitukah',
 'begitulah',
 'begitupun',
 'bekerja',
 'belakang',
 'belakangan',
 'belum',
 'belumlah',
 'benar',
 'benarkah',
 'benarlah',
 'berada',
 'berakhir',
 'berakhirlah',
 'berakhirnya',
 'berapa',
 'berapakah',
 'berapalah',
 'berapapun',
 'berarti',
 'berawal',
 'berbagai',
 'berdatangan',
 'beri',
 'berikan',
 'berikut',
 'berikutnya',
 'berjumlah',
 'berkali-kali',
 'berkata',
 'berkehendak',
 'berkeinginan',
 'berkenaan',
 'berlainan',
 'berlalu',
 'berlangsung',
 'berlebihan',
 'bermacam',
 'bermacam-macam',
 'bermaksud',
 'bermula',
 'bersama',
 'bersama-sama',
 'bersiap',
 'bersiap-siap',
 'bertanya',
 'bertanya-tanya',
 'berturut',
 'berturut-turut',
 'bertutur',
 'berujar',
 'berupa',
 'besar',
 'betul',
 'betulkah',
 'biasa',
 'biasanya',
 'bila',
 'bilakah',
 'bisa',
 'bisakah',
 'boleh',
 'bolehkah',
 'bolehlah',
 'buat',
 'bukan',
 'bukankah',
 'bukanlah',
 'bukannya',
 'bulan',
 'bung',
 'cara',
 'caranya',
 'cukup',
 'cukupkah',
 'cukuplah',
 'cuma',
 'dahulu',
 'dalam',
 'dan',
 'dapat',
 'dari',
 'daripada',
 'datang',
 'dekat',
 'demi',
 'demikian',
 'demikianlah',
 'dengan',
 'depan',
 'di',
 'dia',
 'diakhiri',
 'diakhirinya',
 'dialah',
 'diantara',
 'diantaranya',
 'diberi',
 'diberikan',
 'diberikannya',
 'dibuat',
 'dibuatnya',
 'didapat',
 'didatangkan',
 'digunakan',
 'diibaratkan',
 'diibaratkannya',
 'diingat',
 'diingatkan',
 'diinginkan',
 'dijawab',
 'dijelaskan',
 'dijelaskannya',
 'dikarenakan',
 'dikatakan',
 'dikatakannya',
 'dikerjakan',
 'diketahui',
 'diketahuinya',
 'dikira',
 'dilakukan',
 'dilalui',
 'dilihat',
 'dimaksud',
 'dimaksudkan',
 'dimaksudkannya',
 'dimaksudnya',
 'diminta',
 'dimintai',
 'dimisalkan',
 'dimulai',
 'dimulailah',
 'dimulainya',
 'dimungkinkan',
 'dini',
 'dipastikan',
 'diperbuat',
 'diperbuatnya',
 'dipergunakan',
 'diperkirakan',
 'diperlihatkan',
 'diperlukan',
 'diperlukannya',
 'dipersoalkan',
 'dipertanyakan',
 'dipunyai',
 'diri',
 'dirinya',
 'disampaikan',
 'disebut',
 'disebutkan',
 'disebutkannya',
 'disini',
 'disinilah',
 'ditambahkan',
 'ditandaskan',
 'ditanya',
 'ditanyai',
 'ditanyakan',
 'ditegaskan',
 'ditujukan',
 'ditunjuk',
 'ditunjuki',
 'ditunjukkan',
 'ditunjukkannya',
 'ditunjuknya',
 'dituturkan',
 'dituturkannya',
 'diucapkan',
 'diucapkannya',
 'diungkapkan',
 'dong',
 'dua',
 'dulu',
 'empat',
 'enggak',
 'enggaknya',
 'entah',
 'entahlah',
 'guna',
 'gunakan',
 'hal',
 'hampir',
 'hanya',
 'hanyalah',
 'hari',
 'harus',
 'haruslah',
 'harusnya',
 'hendak',
 'hendaklah',
 'hendaknya',
 'hingga',
 'ia',
 'ialah',
 'ibarat',
 'ibaratkan',
 'ibaratnya',
 'ibu',
 'ikut',
 'ingat',
 'ingat-ingat',
 'ingin',
 'inginkah',
 'inginkan',
 'ini',
 'inikah',
 'inilah',
 'itu',
 'itukah',
 'itulah',
 'jadi',
 'jadilah',
 'jadinya',
 'jangan',
 'jangankan',
 'janganlah',
 'jauh',
 'jawab',
 'jawaban',
 'jawabnya',
 'jelas',
 'jelaskan',
 'jelaslah',
 'jelasnya',
 'jika',
 'jikalau',
 'juga',
 'jumlah',
 'jumlahnya',
 'justru',
 'kala',
 'kalau',
 'kalaulah',
 'kalaupun',
 'kalian',
 'kami',
 'kamilah',
 'kamu',
 'kamulah',
 'kan',
 'kapan',
 'kapankah',
 'kapanpun',
 'karena',
 'karenanya',
 'kasus',
 'kata',
 'katakan',
 'katakanlah',
 'katanya',
 'ke',
 'keadaan',
 'kebetulan',
 'kecil',
 'kedua',
 'keduanya',
 'keinginan',
 'kelamaan',
 'kelihatan',
 'kelihatannya',
 'kelima',
 'keluar',
 'kembali',
 'kemudian',
 'kemungkinan',
 'kemungkinannya',
 'kenapa',
 'kepada',
 'kepadanya',
 'kesampaian',
 'keseluruhan',
 'keseluruhannya',
 'keterlaluan',
 'ketika',
 'khususnya',
 'kini',
 'kinilah',
 'kira',
 'kira-kira',
 'kiranya',
 'kita',
 'kitalah',
 'kok',
 'kurang',
 'lagi',
 'lagian',
 'lah',
 'lain',
 'lainnya',
 'lalu',
 'lama',
 'lamanya',
 'lanjut',
 'lanjutnya',
 'lebih',
 'lewat',
 'lima',
 'luar',
 'macam',
 'maka',
 'makanya',
 'makin',
 'malah',
 'malahan',
 'mampu',
 'mampukah',
 'mana',
 'manakala',
 'manalagi',
 'masa',
 'masalah',
 'masalahnya',
 'masih',
 'masihkah',
 'masing',
 'masing-masing',
 'mau',
 'maupun',
 'melainkan',
 'melakukan',
 'melalui',
 'melihat',
 'melihatnya',
 'memang',
 'memastikan',
 'memberi',
 'memberikan',
 'membuat',
 'memerlukan',
 'memihak',
 'meminta',
 'memintakan',
 'memisalkan',
 'memperbuat',
 'mempergunakan',
 'memperkirakan',
 'memperlihatkan',
 'mempersiapkan',
 'mempersoalkan',
 'mempertanyakan',
 'mempunyai',
 'memulai',
 'memungkinkan',
 'menaiki',
 'menambahkan',
 'menandaskan',
 'menanti',
 'menanti-nanti',
 'menantikan',
 'menanya',
 'menanyai',
 'menanyakan',
 'mendapat',
 'mendapatkan',
 'mendatang',
 'mendatangi',
 'mendatangkan',
 'menegaskan',
 'mengakhiri',
 'mengapa',
 'mengatakan',
 'mengatakannya',
 'mengenai',
 'mengerjakan',
 'mengetahui',
 'menggunakan',
 'menghendaki',
 'mengibaratkan',
 'mengibaratkannya',
 'mengingat',
 'mengingatkan',
 'menginginkan',
 'mengira',
 'mengucapkan',
 'mengucapkannya',
 'mengungkapkan',
 'menjadi',
 'menjawab',
 'menjelaskan',
 'menuju',
 'menunjuk',
 'menunjuki',
 'menunjukkan',
 'menunjuknya',
 'menurut',
 'menuturkan',
 'menyampaikan',
 'menyangkut',
 'menyatakan',
 'menyebutkan',
 'menyeluruh',
 'menyiapkan',
 'merasa',
 'mereka',
 'merekalah',
 'merupakan',
 'meski',
 'meskipun',
 'meyakini',
 'meyakinkan',
 'minta',
 'mirip',
 'misal',
 'misalkan',
 'misalnya',
 'mula',
 'mulai',
 'mulailah',
 'mulanya',
 'mungkin',
 'mungkinkah',
 'nah',
 'naik',
 'namun',
 'nanti',
 'nantinya',
 'nyaris',
 'nyatanya',
 'oleh',
 'olehnya',
 'pada',
 'padahal',
 'padanya',
 'pak',
 'paling',
 'panjang',
 'pantas',
 'para',
 'pasti',
 'pastilah',
 'penting',
 'pentingnya',
 'per',
 'percuma',
 'perlu',
 'perlukah',
 'perlunya',
 'pernah',
 'persoalan',
 'pertama',
 'pertama-tama',
 'pertanyaan',
 'pertanyakan',
 'pihak',
 'pihaknya',
 'pukul',
 'pula',
 'pun',
 'punya',
 'rasa',
 'rasanya',
 'rata',
 'rupanya',
 'saat',
 'saatnya',
 'saja',
 'sajalah',
 'saling',
 'sama',
 'sama-sama',
 'sambil',
 'sampai',
 'sampai-sampai',
 'sampaikan',
 'sana',
 'sangat',
 'sangatlah',
 'satu',
 'saya',
 'sayalah',
 'se',
 'sebab',
 'sebabnya',
 'sebagai',
 'sebagaimana',
 'sebagainya',
 'sebagian',
 'sebaik',
 'sebaik-baiknya',
 'sebaiknya',
 'sebaliknya',
 'sebanyak',
 'sebegini',
 'sebegitu',
 'sebelum',
 'sebelumnya',
 'sebenarnya',
 'seberapa',
 'sebesar',
 'sebetulnya',
 'sebisanya',
 'sebuah',
 'sebut',
 'sebutlah',
 'sebutnya',
 'secara',
 'secukupnya',
 'sedang',
 'sedangkan',
 'sedemikian',
 'sedikit',
 'sedikitnya',
 'seenaknya',
 'segala',
 'segalanya',
 'segera',
 'seharusnya',
 'sehingga',
 'seingat',
 'sejak',
 'sejauh',
 'sejenak',
 'sejumlah',
 'sekadar',
 'sekadarnya',
 'sekali',
 'sekali-kali',
 'sekalian',
 'sekaligus',
 'sekalipun',
 'sekarang',
 'sekarang',
 'sekecil',
 'seketika',
 'sekiranya',
 'sekitar',
 'sekitarnya',
 'sekurang-kurangnya',
 'sekurangnya',
 'sela',
 'selain',
 'selaku',
 'selalu',
 'selama',
 'selama-lamanya',
 'selamanya',
 'selanjutnya',
 'seluruh',
 'seluruhnya',
 'semacam',
 'semakin',
 'semampu',
 'semampunya',
 'semasa',
 'semasih',
 'semata',
 'semata-mata',
 'semaunya',
 'sementara',
 'semisal',
 'semisalnya',
 'sempat',
 'semua',
 'semuanya',
 'semula',
 'sendiri',
 'sendirian',
 'sendirinya',
 'seolah',
 'seolah-olah',
 'seorang',
 'sepanjang',
 'sepantasnya',
 'sepantasnyalah',
 'seperlunya',
 'seperti',
 'sepertinya',
 'sepihak',
 'sering',
 'seringnya',
 'serta',
 'serupa',
 'sesaat',
 'sesama',
 'sesampai',
 'sesegera',
 'sesekali',
 'seseorang',
 'sesuatu',
 'sesuatunya',
 'sesudah',
 'sesudahnya',
 'setelah',
 'setempat',
 'setengah',
 'seterusnya',
 'setiap',
 'setiba',
 'setibanya',
 'setidak-tidaknya',
 'setidaknya',
 'setinggi',
 'seusai',
 'sewaktu',
 'siap',
 'siapa',
 'siapakah',
 'siapapun',
 'sini',
 'sinilah',
 'soal',
 'soalnya',
 'suatu',
 'sudah',
 'sudahkah',
 'sudahlah',
 'supaya',
 'tadi',
 'tadinya',
 'tahu',
 'tahun',
 'tak',
 'tambah',
 'tambahnya',
 'tampak',
 'tampaknya',
 'tandas',
 'tandasnya',
 'tanpa',
 'tanya',
 'tanyakan',
 'tanyanya',
 'tapi',
 'tegas',
 'tegasnya',
 'telah',
 'tempat',
 'tengah',
 'tentang',
 'tentu',
 'tentulah',
 'tentunya',
 'tepat',
 'terakhir',
 'terasa',
 'terbanyak',
 'terdahulu',
 'terdapat',
 'terdiri',
 'terhadap',
 'terhadapnya',
 'teringat',
 'teringat-ingat',
 'terjadi',
 'terjadilah',
 'terjadinya',
 'terkira',
 'terlalu',
 'terlebih',
 'terlihat',
 'termasuk',
 'ternyata',
 'tersampaikan',
 'tersebut',
 'tersebutlah',
 'tertentu',
 'tertuju',
 'terus',
 'terutama',
 'tetap',
 'tetapi',
 'tiap',
 'tiba',
 'tiba-tiba',
 'tidak',
 'tidakkah',
 'tidaklah',
 'tiga',
 'tinggi',
 'toh',
 'tunjuk',
 'turut',
 'tutur',
 'tuturnya',
 'ucap',
 'ucapnya',
 'ujar',
 'ujarnya',
 'umum',
 'umumnya',
 'ungkap',
 'ungkapnya',
 'untuk',
 'usah',
 'usai',
 'waduh',
 'wah',
 'wahai',
 'waktu',
 'waktunya',
 'walau',
 'walaupun',
 'wong',
 'yaitu',
 'yakin',
 'yakni',
 'yang']

In [11]:
# membuat fungsi stopword removal

# menambahkan kata dalam stopwords
more_stopword = ['tsel', 'gb', 'rb', 'btw']
stopwords_ind = stopwords_ind + more_stopword

def remove_stop_word(text):
    clean_words = []
    text = text.split()
    for word in text:
        if word not in stopwords_ind:
            clean_words.append(word)
    return " ".join(clean_words)

In [12]:
raw_sample = data['teks'].iloc[696]
case_folding = casefolding(raw_sample)
stopword_removal = remove_stop_word(case_folding)

print('Raw Data \t\t :', raw_data)
print('Case Folding \t\t :', case_folding)
print('Stopword Reomoval \t\t', stopword_removal)

Raw Data 		 : Belum de.. Saya lagi nyoba ngejar..
Case Folding 		 : belum de saya lagi nyoba ngejar
Stopword Reomoval 		 de nyoba ngejar

## Stemming

In [13]:
!pip -q install sastrawi

[notice] A new release of pip is available: 24.0 -> 26.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [14]:
# merubah kata menjadi kata dasar
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory

factory = StemmerFactory()
stemmer = factory.create_stemmer()

# membuat fungsi untuk stemming bahasa indonesia
def stemming(text):
    text = stemmer.stem(text)
    return text

In [15]:
raw_sample = data['teks'].iloc[696]
case_folding = casefolding(raw_sample)
stopword_removal = remove_stop_word(case_folding)
text_stemming = stemming(stopword_removal)

print('Raw Data \t\t :', raw_sample)
print('Case Folding \t\t :', case_folding)
print('Stopword Removal \t\t :', stopword_removal)
print('Stemming \t\t :', text_stemming)

Raw Data 		 : Belum de.. Saya lagi nyoba ngejar..
Case Folding 		 : belum de saya lagi nyoba ngejar
Stopword Removal 		 : de nyoba ngejar
Stemming 		 : de nyoba ngejar

In [16]:
# membuat fungsi untuk menggabungkan seluruh langkah text preprocessing

def text_preprocessing_process(text) :
    text = casefolding(text)
    text = text_normalize(text)
    text = remove_stop_word(text)
    text = stemming(text)
    return text

In [17]:
%%time
data['clean_teks']= data['teks'].apply(text_preprocessing_process)

CPU times: total: 7min
Wall time: 13min 20s

In [18]:
data

,teks,label,clean_teks
0,IM3 Ooredoo: isi ulang min 50rb hari ini dpt b...,2,im ooredoo isi ulang min bonus kuota malam cek...
1,TSEL-INFO: Paket Combo Sakti 75GB + nelpon sep...,2,tselinfo paket combo sakti telpon puas rprbhr ...
2,XL Axiata khusus pelanggan setia bonus TikTok ...,2,xl axiata khusus langgan setia bonus tiktok un...
3,Smartfren: internet unlimited nonstop mulai 40...,2,smartfren internet unlimited nonstop rbbln str...
4,[PROMO] Beli paket Flash mulai 1GB di MY TELKO...,2,promo beli paket flash my telkomsel app extra ...
...,...,...,...
1191,"Aku lagi di kampus sekarang, dosennya belum da...",0,kampus dosen nunggu
1192,"Maaf baru balas, td ketiduran habis ngerjain t...",0,maaf balas tidur habis tugas kelompok pagi
1193,Tadi ibu bilang nanti malam makan di rumah nen...,0,bilang malam makan rumah nenek kumpul keluarga
1194,Besok jadi bimbingan skripsi jam 10 kan? janga...,0,besok bimbing skripsi jam lupa bawa revisi pro...
1195,"Aku udh sampai rumah tadi jam 7an, jalan macet...",0,rumah jam an jalan macet banget gara hujan der...

In [19]:
# simpan data yang sudah dipreprocessing ke dalam file csv
data.to_csv('clean_data.csv')

## Feature Engineering

In [20]:
# pisahkan kolom feature dan target
x = data['clean_teks']
y = data['label']

In [21]:
x

0       im ooredoo isi ulang min bonus kuota malam cek...
1       tselinfo paket combo sakti telpon puas rprbhr ...
2       xl axiata khusus langgan setia bonus tiktok un...
3       smartfren internet unlimited nonstop rbbln str...
4       promo beli paket flash my telkomsel app extra ...
                              ...
1191                                  kampus dosen nunggu
1192           maaf balas tidur habis tugas kelompok pagi
1193       bilang malam makan rumah nenek kumpul keluarga
1194    besok bimbing skripsi jam lupa bawa revisi pro...
1195    rumah jam an jalan macet banget gara hujan der...
Name: clean_teks, Length: 1196, dtype: object

In [22]:
y

0       2
1       2
2       2
3       2
4       2
       ..
1191    0
1192    0
1193    0
1194    0
1195    0
Name: label, Length: 1196, dtype: int64

## Feature Exraction (TF-IDF dan N-Gram)

In [23]:
# save model
import pickle

#TF IDF
from sklearn.feature_extraction.text import TfidfVectorizer

#Unigram
vec_TF_IDF  = TfidfVectorizer(ngram_range=(1,1))
vec_TF_IDF.fit(x)

x_tf_idf = vec_TF_IDF.transform(x)

pickle.dump(vec_TF_IDF.vocabulary_,open("feature_tf-idf.sav", "wb"))

In [24]:
# menampilkan vocabulary dari tif-idf
vec_TF_IDF.vocabulary_

{'im': 1203,
 'ooredoo': 2134,
 'isi': 1286,
 'ulang': 3170,
 'min': 1873,
 'bonus': 432,
 'kuota': 1610,
 'malam': 1761,
 'cek': 540,
 'aplikasi': 166,
 'myim': 1953,
 'tselinfo': 3114,
 'paket': 2168,
 'combo': 596,
 'sakti': 2611,
 'telpon': 2977,
 'puas': 2408,
 'rprbhr': 2578,
 'aktif': 66,
 'promo': 2382,
 'xl': 3442,
 'axiata': 231,
 'khusus': 1514,
 'langgan': 1639,
 'setia': 2729,
 'tiktok': 3035,
 'unlimited': 3187,
 'biaya': 380,
 'tambah': 2927,
 'via': 3227,
 'myxl': 1956,
 'smartfren': 2809,
 'internet': 1259,
 'nonstop': 2050,
 'rbbln': 2481,
 'streaming': 2868,
 'gaming': 959,
 'batas': 298,
 'favorit': 878,
 'beli': 334,
 'flash': 900,
 'my': 1951,
 'telkomsel': 2974,
 'app': 168,
 'extra': 870,
 'lte': 1716,
 'mnthr': 1901,
 'buru': 497,
 'tselmemytsel': 3118,
 'sk': 2788,
 'axis': 232,
 'warnet': 3258,
 'jam': 1319,
 'ml': 1891,
 'pubg': 2410,
 'ff': 885,
 'axisnet': 234,
 'tri': 3089,
 'indonesia': 1214,
 'guna': 1052,
 'habis': 1061,
 'ya': 3457,
 'tuhan': 3133,
 'sd': 2651,
 'mei': 1822,
 'minrb': 1884,
 'shopee': 2744,
 'gratis': 1041,
 'ongkir': 2127,
 'xtra': 3446,
 'cashback': 529,
 'byu': 505,
 'bikin': 386,
 'langsung': 1642,
 'ribet': 2543,
 'traveloka': 3083,
 'diskon': 746,
 'tiket': 3033,
 'pesawat': 2253,
 'domestik': 770,
 'libur': 1683,
 'pekan': 2213,
 'kode': 1552,
 'tiketcom': 3034,
 'kereta': 1496,
 'api': 164,
 'hotel': 1154,
 'periode': 2243,
 'sekolah': 2672,
 'pesan': 2252,
 'bca': 316,
 'nikmat': 2029,
 'cicil': 570,
 'gadget': 939,
 'elektronik': 836,
 'pilih': 2259,
 'kartu': 1438,
 'kredit': 1588,
 'brimo': 452,
 'transaksi': 3078,
 'qris': 2443,
 'hadiah': 1063,
 'rprb': 2573,
 'laku': 1632,
 'alfamart': 86,
 'produk': 2374,
 'susu': 2905,
 'makan': 1753,
 'ringan': 2551,
 'member': 1829,
 'alfagift': 85,
 'minggu': 1876,
 'gopay': 1031,
 'bayar': 308,
 'tagih': 2921,
 'listrik': 1694,
 'wifi': 3278,
 'pdam': 2207,
 'hemat': 1118,
 'rupiah': 2596,
 'ribu': 2544,
 'spesial': 2848,
 'november': 2065,
 'pulang': 2418,
 'hormat': 1151,
 'sisa': 2781,
 'kb': 1453,
 'download': 781,
 'mytelkomsel': 1954,
 'apps': 173,
 'kuotabeli': 1611,
 'hubung': 1176,
 'skb': 2789,
 'ekstra': 833,
 'pulsa': 2420,
 'bulan': 483,
 'sjk': 2787,
 'augsept': 223,
 'detail': 692,
 'iring': 1281,
 'tarif': 2941,
 'panjang': 2181,
 'hits': 1140,
 'armada': 186,
 'curi': 621,
 'hati': 1103,
 'tekan': 2968,
 'okcall': 2117,
 'informasi': 1229,
 'eks': 830,
 'loh': 1703,
 'internetan': 1260,
 'pakai': 2166,
 'volume': 3235,
 'ultima': 3173,
 'mbhr': 1805,
 'harga': 1091,
 'tariflokasi': 2943,
 'tselmefl': 3116,
 'coboy': 588,
 'jr': 1370,
 'hebat': 1112,
 'baru': 292,
 'noah': 2039,
 'engkau': 845,
 'nya': 2086,
 'hp': 1156,
 'ketik': 1503,
 'mg': 1854,
 'kirim': 1521,
 'berkah': 357,
 'yuni': 3497,
 'shara': 2737,
 'tkn': 3049,
 'raih': 2455,
 'thr': 3025,
 'puluhanjt': 2428,
 'henti': 1120,
 'unreg': 3189,
 'ambil': 101,
 'hari': 1092,
 'bebas': 323,
 'dptkan': 784,
 'sesuai': 2727,
 'hobi': 1147,
 'flashspasiya': 902,
 'tuju': 3134,
 'tunggu': 3144,
 'sms': 2814,
 'konfirmasi': 1572,
 'nonaktif': 2047,
 'mbak': 1802,
 'ghari': 1005,
 'balas': 264,
 'lanjut': 1643,
 'lokasi': 1706,
 'zona': 3502,
 'lihat': 1685,
 'tselmeinternet': 3117,
 'gampang': 960,
 'chatting': 562,
 'bbm': 314,
 'whatsapp': 3272,
 'line': 1689,
 'harijika': 1093,
 'melanjutkantunggu': 1826,
 'pemakaianinfo': 2217,
 'tariff': 2942,
 'terima': 3003,
 'setting': 2733,
 'ponsel': 2335,
 'akses': 64,
 'fotomms': 915,
 'kali': 1414,
 'aktivasi': 68,
 'spasi': 2846,
 'kupon': 1614,
 'program': 2378,
 'as': 193,
 'biber': 381,
 'total': 3070,
 'maksimal': 1758,
 'lengkap': 1672,
 'reguler': 2508,
 'kbdapatkan': 1454,
 'agam': 30,
 'daftar': 631,
 'layan': 1656,
 'voucher': 3237,
 'kenyang': 1489,
 'tukar': 3136,
 'poin': 2326,
 'menang': 1831,
 'hadih': 1069,
 'tinggi': 3040,
 'angpaopoinsenyum': 146,
 'vchr': 3222,
 'lottemart': 1711,
 'normal': 2059,
 'feb': 882,
 'wwwindosatooredoocomangpao': 3360,
 'ayam': 236,
 'sayappaha': 2641,
 'nasi': 1972,
 'perkedel': 2244,
 'teh': 2966,
 'pucuk': 2414,
 'cfc': 554,
 'hasan': 1101,
 'sadikin': 2603,
 'sedia': 2661,
 'ayo': 239,
 'anak': 106,
 'medan': 1815,
 'stiker': 2865,
 'klik': 1534,
 'nama': 1963,
 'stickernya': 2863,
 'dan': 638,
 'appleplay': 170,
 'store': 2867,
 'bronetjam': 460,
 'obor': 2103,
 'ld': 1659,
 'playapple': 2310,
 'dukung': 813,
 'lestari': 1675,
 'alam': 79,
 'indosat': 1216,
 'wwfindonesia': 3296,
 'donasi': 772,
 'nomor': 2044,
 'kawal': 1450,
 'manfaat': 1772,
 'subsidi': 2879,
 'kompensasi': 1566,
 'hak': 1076,
 'adu': 21,
 'banting': 282,
 'desember': 686,
 'ekspresi': 832,
 'diri': 740,
 'freedom': 919,
 'wwwindosatooredoocomfreedom': 3362,
 'internetas': 1261,
 'lychee': 1731,
 'tea': 2961,
 'latte': 1655,
 'flavour': 905,
 'yellow': 3478,
 'truck': 3112,
 'jlpatuha': 1360,
 'berlakupromo': 360,
 'kampung': 1424,
 'gajah': 947,
 'wonderland': 3290,
 'bandung': 272,
 'tunjuk': 3145,
 'tugas': 3129,
 'wwwindosatcomkampunggajah': 3355,
 'donut': 773,
 'dunkin': 817,
 'donuts': 774,
 'borma': 435,
 'setiabudhi': 2730,
 'turbo': 3146,
 'aug': 222,
 'september': 2710,
 'tawar': 2948,
 'januari': 1327,
 'dapetkan': 644,
 'telepon': 2970,
 'april': 175,
 'ooredohanya': 2133,
 'jan': 1325,
 'teman': 2980,
 'menit': 1839,
 'bukti': 480,
 'argo': 183,
 'grabcar': 1035,
 'hayu': 1106,
 'aja': 51,
 'rencang': 2519,
 'bareng': 290,
 'buktikeun': 481,
 'nyalira': 2091,
 'registrasi': 2505,
 'mycare': 1952,
 'dapat': 642,
 'freedoom': 920,
 'butuh': 501,
 'piknikada': 2258,
 'nih': 2026,
 'hongkongcarapake': 1150,
 'androidmu': 137,
 'banyak': 286,
 'items': 1296,
 'pokemon': 2328,
 'gobigococ': 1023,
 'dllinfo': 763,
 'buy': 502,
 'get': 1002,
 'trans': 3077,
 'studio': 2873,
 'bandungmulai': 274,
 'meijuni': 1823,
 'wwwindosatcomtransstudiobgd': 3356,
 'ramadhan': 2459,
 'hg': 1124,
 'pandu': 2177,
 'pan': 2175,
 'ratus': 2475,
 'operator': 2135,
 'komunikasi': 1569,
 'disc': 742,
 'mcdonalds': 1808,
 'tcash': 2954,
 'tapdptkan': 2938,
 'tap': 2937,
 'grapari': 1040,
 'dekat': 668,
 'tselmetappromo': 3119,
 'dominos': 771,
 'pizzaroti': 2299,
 'tebal': 2964,
 'keju': 1468,
 'pinggirmulai': 2278,
 'rpkunjungi': 2571,
 'toko': 3058,
 'terdekattelf': 3001,
 'panpizzacoid': 2182,
 'cappuccino': 519,
 'hotice': 1155,
 'freza': 922,
 'excelso': 866,
 'cafe': 508,
 'semarang': 2690,
 'yogya': 3481,
 'solo': 2835,
 'agust': 42,
 'wendys': 3271,
 'crispy': 613,
 'chicken': 564,
 'sandwich': 2629,
 'minimal': 1879,
 'saldo': 2616,
 'main': 1751,
 'seninkamis': 2704,
 'timezone': 3037,
 'cipika': 575,
 'belanja': 333,
 'kuliner': 1603,
 'fashion': 874,
 'lain': 1630,
 'wwwindosatooredoocom': 3359,
 'dear': 663,
 'customer': 624,
 'kindly': 1518,
 'values': 3220,
 'your': 3482,
 'experience': 868,
 'at': 210,
 'servis': 2723,
 'score': 2648,
 'very': 3226,
 'poor': 2337,
 'excellent': 865,
 'free': 917,
 'intl': 1265,
 'charged': 557,
 'pizza': 2298,
 'value': 3219,
 'range': 2465,
 'agustuskunjungi': 44,
 'terdekathubungi': 3000,
 'visit': 3233,
 'kodevrd': 1554,
 'grab': 1034,
 'urangbandung': 3204,
 'repot': 2522,
 'jalan': 1317,
 'macet': 1739,
 'susah': 2904,
 'parkir': 2189,
 'ngegrab': 2006,
 'we': 3264,
 'atuh': 216,
 'kacamata': 1400,
 'hitam': 1139,
 'gatot': 971,
 'soebroto': 2826,
 'sampk': 2624,
 'pizzarotinya': 2300,
 'pinggir': 2277,
 'double': 778,
 'plus': 2318,
 'rasa': 2469,
 'seru': 2720,
 'gamegame': 954,
 'premium': 2359,
 'dptkn': 785,
 'card': 520,
 'larissa': 1653,
 'aesthetic': 25,
 'center': 549,
 'high': 1131,
 'treatment': 3085,
 'asuransi': 209,
 'jiwa': 1358,
 'galeri': 951,
 'jawa': 1335,
 'diy': 758,
 'des': 685,
 'sempat': 2696,
 'utama': 3216,
 'mobil': 1907,
 'alphard': 96,
 'senyum': 2707,
 'undi': 3180,
 'tanggal': 2932,
 'junketik': 1390,
 'rehabilitasi': 2509,
 'kembang': 1484,
 'potensi': 2346,
 'ypac': 3483,
 'jakarta': 1315,
 'mari': 1783,
 'bagi': 250,
 'etik': 860,
 'agt': 37,
 'datang': 649,
 'gallery': 952,
 'smartfrenmu': 2810,
 'andromax': 138,
 'mifi': 1866,
 'doublescoop': 779,
 'ice': 1185,
 'cream': 610,
 'haagendasz': 1060,
 'ganti': 962,
 'sim': 2765,
 'gerai': 999,
 'indosatooredoo': 1217,
 'jaring': 1331,
 'mana': 1767,
 'js': 1371,
 'masuk': 1793,
 'cobagrabcar': 587,
 'ajak': 55,
 'temantemanmu': 2981,
 'keliling': 1475,
 'tanp': 2935,
 'grabtaxi': 1036,
 'stasiunbandara': 2859,
 'grabtravel': 1037,
 'hatur': 1105,
 'nuhun': 2075,
 'token': 3057,
 'menu': 1844,
 'hai': 1074,
 'kabar': 1397,
 'riah': 2542,
 'minimun': 1881,
 'rla': 2555,
 'hallo': 1078,
 'bro': 458,
 'koin': 1556,
 'games': 957,
 'yuk': 3495,
 'mudah': 1936,
 'banget': 276,
 'sob': 2825,
 'urang': 3203,
 'mang': 1773,
 'ado': 19,
 'rancak': 2462,
 'group': 1042,
 'kampuang': 1423,
 'guy': 1057,
 'musik': 1950,
 'nelpsms': 1984,
 'sekrang': 2673,
 'tlb': 3050,
 'gbgbg': 976,
 'gbg': 974,
 'bronet': 459,
 'bronetspecial': 461,
 'jamgb': 1323,
 'special': 2847,
 'rabu': 2446,
 'blanja': 413,
 'blanjacom': 414,
 'bljcotcashrabu': 417,
 'senin': 2703,
 'nonton': 2051,
 'cema': 547,
 'xxi': 3449,
 'kunjung': 1607,
 'nrml': 2071,
 'lagistok': 1628,
 'terbatassd': 2998,
 'agtskinfodlj': 38,
 'mumpung': 1944,
 'ustad': 3214,
 'fatih': 876,
 'karimbeliau': 1435,
 'islam': 1290,
 'felix': 884,
 'siaw': 2752,
 'hi': 1128,
 'coba': 585,
 'mesan': 1852,
 'taxi': 2949,
 'cepat': 550,
 'aman': 99,
 'hot': 1153,
 'agsts': 36,
 'gbhr': 979,
 'juni': 1387,
 'spreading': 2851,
 'the': 3021,
 'gojek': 1024,
 'love': 1712,
 'and': 109,
 'input': 1241,
 'this': 3024,
 'referral': 2501,
 'code': 591,
 'credit': 611,
 'first': 897,
 'booking': 434,
 'gojekgotmehere': 1025,
 'ikut': 1198,
 'jobfairactive': 1363,
 'ujiklyakankerjaberstifikat': 3166,
 'plasatelkommlg': 2306,
 'platihan': 2308,
 'intrviewrekom': 1266,
 'kerja': 1498,
 'ph': 2255,
 'wwwindogetjobcom': 3352,
 'sumo': 2890,
 'tcashmu': 2955,
 'atm': 214,
 'transfer': 3079,
 'bank': 279,
 'rekening': 2513,
 'hasil': 1102,
 'bimatri': 389,
 'rawit': 2478,
 'jumat': 1385,
 'ibadah': 1182,
 'haji': 1075,
 'nyaman': 2092,
 'lokalnikmati': 1705,
 'menithr': 1840,
 'trima': 3095,
 'indosatooredoointernet': 1219,
 'rprbhariinfo': 2577,
 'pai': 2163,
 'kejar': 1467,
 'lari': 1652,
 'sendiriayo': 2702,
 'sekarangdan': 2671,
 'pasti': 2201,
 'besok': 365,
 'rawitinfold': 2479,
 'lupa': 1727,
 'sesame': 2725,
 'prog': 2377,
 'us': 3208,
 'kalah': 1409,
 'mu': 1933,
 'bantu': 283,
 'baskin': 296,
 'robbins': 2558,
 'scoop': 2647,
 'lho': 1680,
 'infold': 1227,
 'rbnrml': 2487,
 'glte': 1017,
 'gbkonten': 981,
 'tarik': 2944,
 'wwwindosatooredoocomg': 3363,
 'langka': 1641,
 'tld': 3052,
 'flashspasiinfo': 901,
 'status': 2860,
 'loopers': 1710,
 'tren': 3086,
 'muda': 1935,
 'challenge': 555,
 'loopcoid': 1709,
 'followloop': 907,
 'id': 1186,
 'maret': 1782,
 'perbln': 2236,
 'lgs': 1679,
 'gbgbonus': 977,
 'doyan': 782,
 'slm': 2800,
 'oke': 2118,
 'pnwrn': 2325,
 'kocak': 1551,
 'aksi': 65,
 'pemuda': 2224,
 'galau': 949,
 'iseng': 1285,
 'gokil': 1027,
 'kepung': 1493,
 'polisi': 2331,
 'super': 2895,
 'cantik': 515,
 'tonton': 3063,
 'komik': 1563,
 'cmn': 583,
 'film': 892,
 'tinggal': 3039,
 'lanjutin': 1644,
 'gamesmu': 958,
 'data': 647,
 'kuotaspasik': 1613,
 'lets': 1676,
 'rich': 2547,
 'google': 1030,
 'play': 2309,
 'pakettelkomselflash': 2171,
 'gbberlaku': 973,
 'otomatis': 2148,
 'pd': 2206,
 'maaf': 1734,
 'milik': 1870,
 'timur': 3038,
 'bal': 262,
 'lombok': 1707,
 'appsinapps': 174,
 'warung': 3259,
 'kopi': 1578,
 'dki': 760,
 'nsp': 2072,
 'keren': 1495,
 'internetmu': 1262,
 'gift': 1007,
 'paketextra': 2170,
 'smuanya': 2819,
 'install': 1245,
 'file': 890,
 'putus': 2440,
 'gatis': 970,
 'mifimodem': 1867,
 'untuk': 3193,
 'bawa': 304,
 'sf': 2734,
 'sana': 2627,
 'surveu': 2901,
 'singkat': 2776,
 'murah': 1946,
 'juli': 1384,
 'jajan': 1313,
 'kemanamana': 1480,
 'online': 2129,
 'suka': 2883,
 'nge': 1999,
 'jul': 1383,
 'pergi': 2238,
 'aliando': 92,
 'merdeka': 1848,
 'sale': 2617,
 'harirprb': 1096,
 'migrasi': 1868,
 'kartuhalo': 1439,
 'rbbulan': 2482,
 'inipromo': 1238,
 'terbatasskb': 2999,
 'tahap': 2923,
 'ributrip': 2545,
 'nasabah': 1970,
 'btpn': 467,
 'wow': 3292,
 'pin': 2262,
 'rahasia': 2451,
 'panggil': 2178,
 'mall': 1764,
 'sin': 2771,
 'thailand': 3019,
 'hk': 1144,
 'china': 565,
 'usa': 3209,
 'negarano': 1981,
 'wwwindosatooredoocomflatcall': 3361,
 'fried': 923,
 'minum': 1886,
 'junitukarkan': 1389,
 'terbataspromo': 2997,
 'big': 384,
 'pesta': 2254,
 'weekendharga': 3269,
 'rprbberlaku': 2575,
 'dine': 733,
 'intake': 1254,
 'away': 229,
 'maykunjungi': 1799,
 'bakmi': 260,
 'gm': 1018,
 'sli': 2797,
 'negara': 1980,
 'wib': 3273,
 'agustus': 43,
 'wwwindosatcomiddpromo': 3354,
 'chn': 567,
 'mlahkgsngtwnvtmmacau': 1892,
 'ok': 2115,
 'kuat': 1599,
 'tlpsms': 3053,
 'indosatooredoocomfreedom': 1218,
 'agst': 35,
 'visa': 3231,
 'midnight': 1863,
 'ckp': 578,
 'rbminggu': 2486,
 'mbmbbonus': 1806,
 'hggmbpstekan': 1125,
 'syarat': 2910,
 'iur': 1298,
 'bpjs': 439,
 'twallet': 3149,
 'smartphone': 2811,
 'android': 136,
 'iphone': 1276,
 'mini': 1878,
 'sn': 2820,
 'netmax': 1987,
 'situs': 2785,
 'tricoid': 3093,
 'untung': 3194,
 'tes': 3011,
 'identitas': 1188,
 'vd': 3223,
 'handphone': 1080,
 'myxlcoid': 1957,
 'restart': 2532,
 'minta': 1885,
 'kena': 1485,
 'dasar': 646,
 'skema': 2790,
 'wwwtelkomselcom': 3423,
 'temu': 2992,
 'non': 2046,
 'kebut': 1460,
 'pcs': 2205,
 'strip': 2870,
 'sayapnasiteh': 2640,
 'rptukarkan': 2581,
 'subang': 2877,
 'iniselama': 1239,
 'adapromo': 12,
 'mar': 1778,
 'ubah': 3157,
 'cukup': 619,
 'off': 2108,
 'update': 3196,
 'tselmeas': 3115,
 'daves': 651,
 'single': 2777,
 'burger': 495,
 'small': 2807,
 'fries': 924,
 'obral': 2104,
 'gbnelpon': 982,
 'minggudaftar': 1877,
 'rtx': 2586,
 'ythmohon': 3488,
 'nilai': 2031,
 'bahasa': 255,
 'type': 3152,
 'english': 846,
 'sdnov': 2653,
 'dlk': 762,
 'tselpoin': 3121,
 'facebook': 871,
 'video': 3228,
 'quota': 2444,
 'merchant': 1846,
 'voice': 3234,
 'ri': 2541,
 'ags': 34,
 'miring': 1887,
 'bagus': 251,
 'bolak': 430,
 'pulsacek': 2423,
 'rprbbln': 2576,
 'gbggb': 978,
 'gmau': 1020,
 'gbgb': 975,
 'pindah': 2273,
 'jljend': 1359,
 'soedirmanpurwokerto': 2827,
 'bns': 424,
 'selamat': 2674,
 'berrybenka': 362,
 'twd': 3150,
 'wwwberrybenkacomsimpati': 3305,
 'lazada': 1658,
 'tst': 3123,
 'wwwlazadacoidsimpati': 3392,
 'zalora': 3499,
 'tsu': 3124,
 'wwwzaloracoidsimpati': 3440,
 'gabung': 937,
 'harikuota': 1094,
 'lipat': 1691,
 'aktivitas': 69,
 'statusberhenti': 2861,
 'pas': 2191,
 'instink': 1251,
 'cs': 614,
 'selamatanda': 2675,
 'smsgift': 2815,
 'sensasi': 2705,
 'game': 953,
 'heroes': 1122,
 'hit': 1138,
 'ball': 266,
 'pool': 2336,
 'gmmu': 1021,
 'limpah': 1688,
 'luculucu': 1719,
 'ckup': 579,
 'akumulasi': 71,
 'tlc': 3051,
 'mataharimall': 1795,
 'gaya': 972,
 'hidup': 1130,
 'kasih': 1443,
 'sahabat': 2608,
 'kenal': 1486,
 'yaok': 3474,
 'heboh': 1113,
 'artisartis': 188,
 'top': 3064,
 'menittlp': 1841,
 'menitvideo': 1842,
 'yesok': 3479,
 'kini': 1519,
 'ungkapin': 3184,
 'pikir': 2257,
 'stickershop': 2864,
 'aneka': 139,
 'merchants': 1847,
 'partner': 2190,
 'thank': 3020,
 'appreciation': 172,
 'percaya': 2237,
 'in': 1205,
 'using': 3213,
 'further': 930,
 'feedback': 883,
 'mohon': 1917,
 'nasehat': 1971,
 'text': 3014,
 'freefor': 921,
 'tingkat': 3041,
 'rpribu': 2579,
 'pernuh': 2246,
 'dapet': 643,
 'trmksh': 3104,
 'jual': 1377,
 'pulsabayar': 2422,
 'listrikspeedytelkom': 1695,
 'hubagen': 1166,
 'barokahmp': 291,
 'reloadpasti': 2515,
 'up': 3195,
 'coins': 592,
 'themes': 3022,
 'koleksi': 1559,
 'use': 3212,
 'nxmvfue': 2085,
 'ride': 2548,
 'redeem': 2499,
 'it': 1295,
 'penuh': 2232,
 'batasankami': 299,
 'kebebasa': 1458,
 'kuotacuma': 1612,
 'dengerin': 675,
 'seleb': 2681,
 'blog': 419,
 'suara': 2876,
 'rpmggcs': 2572,
 'vas': 3221,
 'fb': 879,
 'twitter': 3151,
 'temen': 2984,
 'bioskop': 393,
 'keluarga': 1478,
 'cigna': 571,
 'bitlytentangcigna': 406,
 'yuks': 3496,
 'seruseruan': 2721,
 'resmi': 2529,
 'tunai': 3141,
 'jt': 1372,
 'gebyar': 985,
 'nasional': 1977,
 'klaim': 1530,
 'xxxxxx': 3453,
 'akun': 72,
 'mbanking': 1803,
 'silah': 2763,
 'verifikasi': 3224,
 'bitlybcalogin': 402,
 'tahan': 2922,
 'gudang': 1050,
 'jne': 1361,
 'alamat': 80,
 'resi': 2524,
 'admin': 16,
 'sidcekpaket': 2756,
 'langgar': 1640,
 'sistem': 2783,
 'otp': 2149,
 'hindar': 1136,
 'blokir': 421,
 'sosial': 2840,
 'bantuanresmimyid': 284,
 'danaid': 640,
 'login': 1701,
 'perangkat': 2235,
 'surabaya': 2896,
 'bitlydanaverif': 403,
 'uang': 3153,
 'hadiahpoincom': 1066,
 'unit': 3186,
 'pro': 2372,
 'acara': 8,
 'pusat': 2432,
 'pajak': 2164,
 'kendara': 1488,
 'bb': 311,
 'xx': 3448,
 'tunggak': 3142,
 'denda': 673,
 'taut': 2947,
 'shopeepay': 2745,
 'bitlyshopeelogin': 405,
 'permanen': 2245,
 'nik': 2027,
 'kk': 1527,
 'registrasionlinemyid': 2506,
 'avanza': 225,
 'administrasi': 17,
 'tanggung': 2933,
 'juta': 1393,
 'mobile': 1908,
 'banking': 281,
 'tinyurlcomverifikasimbank': 3042,
 'ovoid': 2155,
 'alami': 81,
 'ilegal': 1199,
 ...}

In [25]:
# melihat jumlah feature
print(len(vec_TF_IDF.get_feature_names_out()))

3504

In [26]:
# melihat fitur apa saja yang ada didalam corpus
print(vec_TF_IDF.get_feature_names_out())

['aa' 'aamiiiin' 'aamiin' ... 'zjt' 'zona' 'ztkm']

In [27]:
x1 =  vec_TF_IDF.transform(x).toarray()
data_tabular_tf_idf = pd.DataFrame(x1,columns=vec_TF_IDF.get_feature_names_out())
data_tabular_tf_idf

,aa,aamiiiin,aamiin,ab,abadi,abai,abbee,abdul,acara,acaratks,...,yudisium,yuk,yuks,yuni,yunit,zalora,zarkasi,zjt,zona,ztkm
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1191,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1192,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1193,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1194,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1195,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [28]:
data_tabular_tf_idf.iloc[10:20,60:70]

,akang,akangteteh,akbar,akreditasi,akses,aksi,aktif,aktifasi,aktivasi,aktivitas
10,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0
11,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0
12,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0
13,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0
14,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0
15,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0
16,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0
17,0.0,0.0,0.0,0.0,0.0,0.0,0.510644,0.0,0.0,0.0
18,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0
19,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0

## Feature Selection

In [29]:
x_train = np.array(data_tabular_tf_idf)
y_train = np.array(y)

In [30]:
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2

chi2_features = SelectKBest(chi2, k=3000)
x_kbest_features = chi2_features.fit_transform(x_train, y_train)

# untuk reduced features
print('Original Feature Number', x_train.shape[1])
print('Reduced feature Number', x_kbest_features.shape[1])

Original Feature Number 3504
Reduced feature Number 3000

In [31]:
Data = pd.DataFrame(chi2_features.scores_,columns=['Nilai'])
Data

         Nilai
0     0.875776
1     0.432501
2     1.604932
3     0.677454
4     0.749100
...        ...
3499  1.102668
3500  0.497342
3501  0.677454
3502  2.850606
3503  0.824003

[3504 rows x 1 columns]

In [32]:
# menampilkan feature beserta nilainya

feature = vec_TF_IDF.get_feature_names_out()
feature

Data['Fitur'] = feature
Data

         Nilai     Fitur
0     0.875776        aa
1     0.432501  aamiiiin
2     1.604932    aamiin
3     0.677454        ab
4     0.749100     abadi
...        ...       ...
3499  1.102668    zalora
3500  0.497342   zarkasi
3501  0.677454       zjt
3502  2.850606      zona
3503  0.824003      ztkm

[3504 rows x 2 columns]

In [33]:
# mengurutkan nilai feature terbaik
Data.sort_values(by='Nilai', ascending=False)

          Nilai   Fitur
2168  48.648500   paket
1610  45.393808   kuota
1063  44.168464  hadiah
2262  37.049033     pin
334   35.412682    beli
...         ...     ...
1485   0.051857    kena
1885   0.046576   minta
1578   0.041063    kopi
962    0.016392   ganti
550    0.000716   cepat

[3504 rows x 2 columns]

In [34]:
data['label'].unique()

array([2, 1, 0])

In [35]:
kata = "hadiah"

for label in data['label'].unique():
    subset = data[data['label'] == label]
    muncul = subset['clean_teks'].apply(lambda t: kata in str(t).split()).sum()
    tidak_muncul = len(subset) - muncul
    print(f"Label {label} -> muncul: {muncul}, tidak muncul: {tidak_muncul}, total: {len(subset)}")

Label 2 -> muncul: 3, tidak muncul: 252, total: 255
Label 1 -> muncul: 117, tidak muncul: 237, total: 354
Label 0 -> muncul: 1, tidak muncul: 586, total: 587

In [36]:
mask = chi2_features.get_support()
mask

array([ True,  True,  True, ...,  True,  True,  True], shape=(3504,))

In [37]:
# menampilkan fitur yang terpilih berdasarkan nilai mask atau nilai tertinggi yang sudah ditetapkan pada chi square

new_feature=[]
for bool, f in zip(mask, feature):
    if bool :
        new_feature.append(f)
    selected_feature=new_feature
selected_feature

['aa',
 'aamiiiin',
 'aamiin',
 'ab',
 'abadi',
 'abai',
 'abbee',
 'abdul',
 'acara',
 'acaratks',
 'ada',
 'adapromo',
 'adi',
 'adik',
 'admin',
 'administrasi',
 'adminlte',
 'ado',
 'adrian',
 'adu',
 'aduh',
 'advertising',
 'aea',
 'aesthetic',
 'afbe',
 'affc',
 'afr',
 'afrika',
 'agam',
 'agen',
 'agendain',
 'agenpulsa',
 'ags',
 'agst',
 'agsts',
 'agt',
 'agtskinfodlj',
 'agua',
 'agun',
 'agus',
 'agust',
 'agustuskunjungi',
 'ahaha',
 'ahub',
 'aigoo',
 'air',
 'ajaa',
 'ajaaa',
 'ajabri',
 'ajak',
 'ajar',
 'ajeng',
 'akademik',
 'akang',
 'akbar',
 'akreditasi',
 'akses',
 'aksi',
 'aktif',
 'aktifasi',
 'aktivasi',
 'aktivitas',
 'akucintaislam',
 'akumulasi',
 'akun',
 'akurasi',
 'akurat',
 'alaikum',
 'alaikumsaya',
 'alaiqum',
 'alam',
 'alamat',
 'alamsyah',
 'alesannya',
 'alfagift',
 'alfamart',
 'algoritma',
 'alhamdulillah',
 'alhuda',
 'ali',
 'aliando',
 'all',
 'allah',
 'alphard',
 'alquran',
 'aman',
 'amanda',
 'ambil',
 'amin',
 'ampuun',
 'an',
 'anabdullah',
 'anak',
 'anakanak',
 'ananda',
 'and',
 'anda',
 'andaafr',
 'andabch',
 'andabfgs',
 'andac',
 'andadidinfo',
 'andaerd',
 'andafah',
 'andafe',
 'andafg',
 'andahhh',
 'andaijhk',
 'andajf',
 'andam',
 'andamcxj',
 'andarman',
 'andasyaratcopy',
 'andatb',
 'andaxvf',
 'andaxxxxx',
 'andaytg',
 'andi',
 'andika',
 'andipublishercompobnibank',
 'andrianto',
 'androidmu',
 'andromax',
 'aneka',
 'ang',
 'angga',
 'angin',
 'angka',
 'angkot',
 'angpaopoinsenyum',
 'angsur',
 'angunan',
 'ani',
 'animasi',
 'anomali',
 'anrasto',
 'antar',
 'antivirus',
 'anu',
 'anwahyudi',
 'anyar',
 'anyonghaseyo',
 'ap',
 'apa',
 'api',
 'apiapi',
 'aplikasi',
 'apotek',
 'app',
 'apple',
 'appleplay',
 'apply',
 'appreciation',
 'apps',
 'appsinapps',
 'april',
 'aqila',
 'aqua',
 'ardiansa',
 'ardiansah',
 'ardiansyah',
 'area',
 'arengnya',
 'argo',
 'ari',
 'arif',
 'armada',
 'artha',
 'artisartis',
 'arum',
 'arya',
 'aryadhi',
 'aryaxxx',
 'as',
 'asa',
 'asalasalan',
 'ashar',
 'asing',
 'asli',
 'ass',
 'assalamu',
 'assalamualaikum',
 'assmaaf',
 'asssy',
 'asuransi',
 'at',
 'atas',
 'atauhub',
 'atay',
 'ato',
 'atuh',
 'atuhlah',
 'aty',
 'au',
 'aug',
 'augsept',
 'aunul',
 'avanza',
 'avanzadari',
 'away',
 'awet',
 'axiata',
 'axis',
 'axismu',
 'axisnet',
 'ayah',
 'ayam',
 'ayena',
 'ayeuna',
 'ayo',
 'ayook',
 'ayu',
 'ayyuuuukk',
 'babakaran',
 'badan',
 'bagi',
 'bahagia',
 'bahan',
 'bahas',
 'bahaya',
 'baik',
 'bakar',
 'bakmi',
 'bakti',
 'balai',
 'balas',
 'balitrims',
 'ball',
 'balon',
 'bambang',
 'bandar',
 'bandara',
 'bandros',
 'bandung',
 'bandungg',
 'bandungmulai',
 'bang',
 'banget',
 'bangun',
 'bangunin',
 'bank',
 'bankbni',
 'banking',
 'banting',
 'bantuanresmimyid',
 'bantuin',
 'banyak',
 'bapa',
 'bapak',
 'bareng',
 'barokahmp',
 'baru',
 'baruqskrng',
 'barusan',
 'basdat',
 'baskin',
 'batam',
 'batas',
 'batasankami',
 'batasfupkecepatan',
 'bati',
 'batin',
 'batman',
 'bawa',
 'bawain',
 'bayang',
 'bayar',
 'bayardi',
 'bayu',
 'bb',
 'bbade',
 'bbd',
 'bbm',
 'bc',
 'bca',
 'bcainfo',
 'bch',
 'bchuinfo',
 'bddfd',
 'beaok',
 'beban',
 'bebas',
 'bebek',
 'beberes',
 'beda',
 'begitusayang',
 'bekas',
 'beku',
 'belanja',
 'beli',
 'beliau',
 'belikan',
 'belikn',
 'beliung',
 'bella',
 'belok',
 'beneran',
 'bensin',
 'bentar',
 'bentuk',
 'berangkat',
 'berangkt',
 'berapaa',
 'beras',
 'berat',
 'beres',
 'berfikir',
 'berita',
 'berkah',
 'berkas',
 'berkat',
 'berlakupromo',
 'berminatsy',
 'berrybenka',
 'besok',
 'besoook',
 'besto',
 'beu',
 'bfgs',
 'bget',
 'bgi',
 'bgmana',
 'bh',
 'bhw',
 'bhwa',
 'bi',
 'biar',
 'biasana',
 'biaya',
 'biber',
 'bicara',
 'big',
 'bih',
 'bikin',
 'bilang',
 'bimatri',
 'bimbing',
 'bingung',
 'bintang',
 'bioskop',
 'bip',
 'bis',
 'bisah',
 'bisakami',
 'bisangga',
 'bisnis',
 'bisns',
 'bitlybcalogin',
 'bitlydanaverif',
 'bitlyloginbcaid',
 'bitlyshopeelogin',
 'bitlytentangcigna',
 'bjam',
 'bl',
 'bla',
 'blackberry',
 'blackberrydakota',
 'blackberryiphone',
 'blanja',
 'blanjacom',
 'bliin',
 'bliung',
 'bljcotcashrabu',
 'bljrpenguatan',
 'blog',
 'blogspotcom',
 'blokir',
 'bni',
 'bns',
 'bntar',
 'bobo',
 'bobok',
 'bocor',
 'boladpt',
 'bolak',
 'bonus',
 'bonusnyacekbns',
 'booking',
 'borma',
 'bos',
 'bpa',
 'bpjs',
 'bpkb',
 'bpkbsertipikatproses',
 'bpkdedy',
 'bpkibu',
 'bpkyogi',
 'bpr',
 'brati',
 'brencana',
 'brgkt',
 'brh',
 'bri',
 'brianasri',
 'brimo',
 'brinorekanir',
 'britama',
 'brminat',
 'brminatcocoktlong',
 'bro',
 'bronet',
 'bronetjam',
 'bronetspecial',
 'brpnya',
 'brsik',
 'brunya',
 'bsediasms',
 'btpn',
 'bu',
 'buat',
 'buatau',
 'bubuka',
 'budget',
 'bug',
 'buka',
 'bukti',
 'buktikeun',
 'buku',
 'bulan',
 'buletdatar',
 'bully',
 'bumbu',
 'bumiputera',
 'bunas',
 'bunda',
 'bunga',
 'bungkus',
 'burger',
 'bursa',
 'buru',
 'buruk',
 'business',
 'buy',
 'bwrangkat',
 'by',
 'byu',
 'cabai',
 'cafe',
 'cahaya',
 'cair',
 'callsms',
 'camera',
 'cantik',
 'capai',
 'capek',
 'cappuccino',
 'card',
 'care',
 'carecom',
 'careselamat',
 'cari',
 'cas',
 'cashback',
 'cashkredit',
 'casino',
 'caturgadgetymailcom',
 'cc',
 'ccfa',
 'cckt',
 'cckta',
 'cecer',
 'cegah',
 'cek',
 'cekrpjuta',
 'cektunai',
 'celaka',
 'celana',
 'cell',
 'celluler',
 'cema',
 'cenah',
 'cerita',
 'cewek',
 'cfc',
 'challenge',
 'chandra',
 'charged',
 'chartered',
 'chat',
 'chatnya',
 'chatnyaa',
 'chatting',
 'cheking',
 'chicken',
 'china',
 'chip',
 'chn',
 'ciateul',
 'cicil',
 'cigna',
 'cilimus',
 'cip',
 'cipika',
 'ciprat',
 'city',
 'ckp',
 'ckup',
 'client',
 'clip',
 'cliponyu',
 'cnf',
 'coba',
 'cobagrabcar',
 'coboy',
 'cochochips',
 'cocok',
 'code',
 'coins',
 'cokelat',
 'colok',
 'com',
 'combo',
 'construct',
 'controler',
 'controller',
 'controllernya',
 'copy',
 'corp',
 'costumer',
 'cover',
 'cowok',
 'cowonya',
 'cp',
 'cpy',
 'cream',
 'credit',
 'creditcard',
 'crispy',
 'cs',
 'csps',
 'cuaca',
 'cuci',
 'curi',
 'curiga',
 'cuss',
 'customer',
 'cuti',
 'da',
 'dacota',
 'dadak',
 'daerah',
 'daging',
 'dahsyat',
 'dakota',
 'dakotajt',
 'dakwah',
 'dambil',
 'dan',
 'dana',
 'danaid',
 'danamon',
 'dapat',
 'dapet',
 'dapetkan',
 'daptkn',
 'data',
 'database',
 'datang',
 'daun',
 'daves',
 'davis',
 'davisrb',
 'daya',
 'db',
 'dblkg',
 'dcs',
 'dddss',
 'ddmmyyyy',
 'de',
 'deadline',
 'dear',
 'debat',
 'dediktp',
 'dee',
 'deh',
 'dekat',
 'dekstop',
 'delete',
 'demam',
 'demo',
 'denda',
 'dengar',
 'dengerin',
 'dengna',
 'denpasar',
 'depaaan',
 'depan',
 'deposit',
 'deras',
 'dermawan',
 'derr',
 'desember',
 'desi',
 'desila',
 'desilla',
 'desjan',
 'desy',
 'detail',
 'dgninternetgaul',
 'dhi',
 'diagnosa',
 'diantapani',
 'dianterin',
 'diapain',
 'dibawain',
 'dibutuhin',
 'dicontroler',
 'did',
 'diem',
 'digantiin',
 'diiket',
 'diil',
 'dijadiin',
 'dijmput',
 'dikosan',
 'dikostan',
 'dikpad',
 'dikti',
 'dil',
 'dila',
 'diload',
 'dimasukin',
 'dinas',
 'dinding',
 'dine',
 'diomongin',
 'diperpanjangnikmati',
 'diprog',
 'direktur',
 'direpository',
 'diri',
 'disatuin',
 'disc',
 'discond',
 'discound',
 'disesuaikanlebih',
 'diskon',
 'diskusi',
 'disurvey',
 'dit',
 'ditelfon',
 'diteruskanbayar',
 'ditks',
 'ditravel',
 'diwwwmytrijimdocom',
 'diy',
 'djunaedi',
 'dki',
 'dlk',
 'dllinfo',
 'dluuntuk',
 'doa',
 'dokter',
 'dokumen',
 'dolar',
 'domestic',
 'domestik',
 'dominos',
 'donasi',
 'donut',
 'donuts',
 'dooong',
 'dosa',
 'dosen',
 'double',
 'doublescoop',
 'down',
 'download',
 'doyan',
 'dp',
 'dptkan',
 'dptkn',
 'drhdarmawan',
 'drhirawan',
 'drhjsopian',
 'driver',
 'dropdown',
 'drpengundian',
 'drptindosat',
 'drrimbawandirmawa',
 'drsh',
 'drshmulyadi',
 'drshnaldisuparman',
 'drshsrianto',
 'dscn',
 'dss',
 'dtggu',
 'dtng',
 'dua',
 'duaduanya',
 'duduk',
 'duh',
 'duit',
 'dukung',
 'duluan',
 'dummy',
 'dunkin',
 'dwi',
 'dwm',
 'dyhaha',
 'edan',
 'edisi',
 'edit',
 'efgr',
 'eh',
 'eks',
 'ekspresi',
 'ekstra',
 'elecktronik',
 'elektrik',
 'elektronik',
 'email',
 'emang',
 'emasasia',
 'emlb',
 'enak',
 'enakaa',
 'end',
 'engkau',
 'english',
 'enhaii',
 'entenipenteng',
 'er',
 'error',
 'errorhrus',
 'ertiga',
 'es',
 'essay',
 'estimasi',
 'eta',
 'etik',
 'etiket',
 'euy',
 'ewu',
 'excellent',
 'excelso',
 'experience',
 'extra',
 'facebook',
 'fany',
 'farida',
 'fashion',
 'fatih',
 'fatima',
 'favorit',
 'fc',
 'fcopy',
 'feb',
 'feedback',
 'felix',
 'ff',
 'fg',
 'fhjtl',
 'fhx',
 'file',
 'filenya',
 'film',
 'finance',
 'fip',
 'fir',
 'firli',
 'first',
 'fitutnya',
 'fix',
 'flash',
 'flashspasiinfo',
 'flashspasiya',
 'flat',
 'flatbln',
 'flavour',
 'followloop',
 'food',
 'form',
 'formnya',
 'foto',
 'fotomms',
 'fpmipa',
 'free',
 'freed',
 'freedom',
 'freedoom',
 'freefor',
 'freza',
 'fried',
 'fries',
 'friska',
 'frown',
 'ft',
 'fungsi',
 'further',
 'futsal',
 'gaaa',
 'gaaaa',
 'gaaais',
 'gaaak',
 'gabung',
 'gadget',
 'gadiabsen',
 'gaes',
 'gaga',
 'gagal',
 'gaib',
 'gais',
 'gajah',
 'gaji',
 'galau',
 'galaxy',
 'galeri',
 'gallery',
 'game',
 'gamegame',
 'gamepro',
 'gameprog',
 'games',
 'gamesmu',
 'gaming',
 'gampang',
 'gang',
 'gantiinpenting',
 'gara',
 'garsindo',
 'gas',
 'gateway',
 'gatis',
 'gatot',
 'gbberlaku',
 'gbg',
 'gbgb',
 'gbgbg',
 'gbgbonus',
 'gbggb',
 'gbhr',
 'gbjt',
 'gbkonten',
 'gbnelpon',
 'ge',
 'gebyar',
 'gedorin',
 'gedung',
 'gelang',
 'gelas',
 'geleh',
 'gemastik',
 'gemini',
 'geminirbq',
 'gempa',
 'geng',
 'gening',
 'genuine',
 'gera',
 'gerai',
 'gerbang',
 'gerlong',
 'get',
 'getlucky',
 'gf',
 'ghari',
 'gi',
 'gift',
 'gigi',
 'gik',
 'gila',
 'gilisms',
 'git',
 'gita',
 'github',
 'gituch',
 'gitulah',
 'glte',
 'gm',
 'gmana',
 'gmau',
 'gmmu',
 'gnkan',
 'gobigococ',
 'gojek',
 'gojekgotmehere',
 'gokil',
 'goldjt',
 'gombal',
 'google',
 'gopay',
 'goreng',
 'gorengin',
 'grab',
 'grabcar',
 'grabtaxi',
 'grabtravel',
 'graha',
 'grand',
 'grapari',
 'gratis',
 'groupwhere',
 'groupwherenya',
 'grup',
 'gsm',
 'gsmcdmavvutk',
 'gtau',
 'gtshop',
 'gudang',
 'gum',
 'guna',
 'gunakn',
 'guntur',
 'guru',
 'gusti',
 'guy',
 'guys',
 'gymnas',
 'haagendasz',
 'habis',
 'hadap',
 'hadiah',
 'hadiahkunjungi',
 'hadiahlik',
 'hadiahpoincom',
 'hadiahrp',
 'hadian',
 'hadih',
 'hadir',
 'haha',
 'hahaha',
 'hahahaha',
 'haji',
 'hak',
 'halang',
 'hallo',
 'haluan',
 'handphone',
 'hanum',
 'har',
 'harap',
 'hardcover',
 'harddisk',
 'harga',
 'hari',
 'harijika',
 'harikuota',
 'harino',
 'harirprb',
 'haris',
 'hartanto',
 'harum',
 'hasan',
 'hasil',
 'hati',
 'hatta',
 'hatur',
 'hayu',
 'hbngi',
 'hd',
 'hdr',
 'hdrjn',
 'heboh',
 'hehe',
 'hehehe',
 'helmkuuuu',
 'hemat',
 'hendra',
 'henti',
 'hermawati',
 'heroes',
 'heula',
 'hg',
 'hggmbpstekan',
 'hhb',
 'hher',
 'hi',
 'hibur',
 'high',
 'hihi',
 'hihip',
 'hihu',
 'hijau',
 'hindar',
 'hirenya',
 'hit',
 'hits',
 'hitung',
 'hj',
 'hjsuri',
 'hk',
 'hmm',
 'hmmm',
 'hobi',
 'honda',
 'hongkongcarapake',
 'hormat',
 'host',
 'hot',
 'hotel',
 'hotice',
 'hp',
 'hpjam',
 'hpnya',
 'hpterima',
 'hquarters',
 'hrap',
 'hrian',
 'hsulaiman',
 ...]

In [38]:
# membuat vocabulary baru berdasarkan fitur yang terseleksi

new_selection_feature = {}

for (k,v) in vec_TF_IDF.vocabulary_.items():
    if k in selected_feature:
        new_selection_feature[k]=v

new_selection_feature

{'im': 1203,
 'ooredoo': 2134,
 'isi': 1286,
 'ulang': 3170,
 'min': 1873,
 'bonus': 432,
 'kuota': 1610,
 'malam': 1761,
 'cek': 540,
 'aplikasi': 166,
 'myim': 1953,
 'tselinfo': 3114,
 'paket': 2168,
 'combo': 596,
 'sakti': 2611,
 'telpon': 2977,
 'puas': 2408,
 'rprbhr': 2578,
 'aktif': 66,
 'promo': 2382,
 'xl': 3442,
 'axiata': 231,
 'khusus': 1514,
 'langgan': 1639,
 'setia': 2729,
 'tiktok': 3035,
 'unlimited': 3187,
 'biaya': 380,
 'tambah': 2927,
 'myxl': 1956,
 'smartfren': 2809,
 'internet': 1259,
 'nonstop': 2050,
 'rbbln': 2481,
 'streaming': 2868,
 'gaming': 959,
 'batas': 298,
 'favorit': 878,
 'beli': 334,
 'flash': 900,
 'my': 1951,
 'telkomsel': 2974,
 'app': 168,
 'extra': 870,
 'lte': 1716,
 'mnthr': 1901,
 'buru': 497,
 'tselmemytsel': 3118,
 'sk': 2788,
 'axis': 232,
 'warnet': 3258,
 'jam': 1319,
 'ml': 1891,
 'pubg': 2410,
 'ff': 885,
 'axisnet': 234,
 'tri': 3089,
 'indonesia': 1214,
 'guna': 1052,
 'habis': 1061,
 'ya': 3457,
 'tuhan': 3133,
 'sd': 2651,
 'mei': 1822,
 'minrb': 1884,
 'shopee': 2744,
 'gratis': 1041,
 'ongkir': 2127,
 'xtra': 3446,
 'cashback': 529,
 'byu': 505,
 'bikin': 386,
 'langsung': 1642,
 'ribet': 2543,
 'traveloka': 3083,
 'diskon': 746,
 'tiket': 3033,
 'pesawat': 2253,
 'domestik': 770,
 'libur': 1683,
 'pekan': 2213,
 'kode': 1552,
 'tiketcom': 3034,
 'kereta': 1496,
 'api': 164,
 'hotel': 1154,
 'periode': 2243,
 'pesan': 2252,
 'bca': 316,
 'nikmat': 2029,
 'cicil': 570,
 'gadget': 939,
 'elektronik': 836,
 'pilih': 2259,
 'kartu': 1438,
 'kredit': 1588,
 'brimo': 452,
 'transaksi': 3078,
 'qris': 2443,
 'hadiah': 1063,
 'rprb': 2573,
 'laku': 1632,
 'alfamart': 86,
 'produk': 2374,
 'susu': 2905,
 'makan': 1753,
 'ringan': 2551,
 'member': 1829,
 'alfagift': 85,
 'minggu': 1876,
 'gopay': 1031,
 'bayar': 308,
 'tagih': 2921,
 'listrik': 1694,
 'wifi': 3278,
 'pdam': 2207,
 'hemat': 1118,
 'rupiah': 2596,
 'ribu': 2544,
 'spesial': 2848,
 'november': 2065,
 'pulang': 2418,
 'hormat': 1151,
 'sisa': 2781,
 'kb': 1453,
 'download': 781,
 'mytelkomsel': 1954,
 'apps': 173,
 'kuotabeli': 1611,
 'hubung': 1176,
 'skb': 2789,
 'ekstra': 833,
 'pulsa': 2420,
 'bulan': 483,
 'sjk': 2787,
 'augsept': 223,
 'detail': 692,
 'iring': 1281,
 'tarif': 2941,
 'panjang': 2181,
 'hits': 1140,
 'armada': 186,
 'curi': 621,
 'hati': 1103,
 'tekan': 2968,
 'okcall': 2117,
 'informasi': 1229,
 'eks': 830,
 'loh': 1703,
 'internetan': 1260,
 'pakai': 2166,
 'volume': 3235,
 'ultima': 3173,
 'mbhr': 1805,
 'harga': 1091,
 'tariflokasi': 2943,
 'tselmefl': 3116,
 'coboy': 588,
 'jr': 1370,
 'baru': 292,
 'noah': 2039,
 'engkau': 845,
 'nya': 2086,
 'hp': 1156,
 'ketik': 1503,
 'mg': 1854,
 'kirim': 1521,
 'berkah': 357,
 'yuni': 3497,
 'shara': 2737,
 'tkn': 3049,
 'raih': 2455,
 'thr': 3025,
 'puluhanjt': 2428,
 'henti': 1120,
 'unreg': 3189,
 'ambil': 101,
 'hari': 1092,
 'bebas': 323,
 'dptkan': 784,
 'sesuai': 2727,
 'hobi': 1147,
 'flashspasiya': 902,
 'tuju': 3134,
 'tunggu': 3144,
 'sms': 2814,
 'nonaktif': 2047,
 'mbak': 1802,
 'ghari': 1005,
 'balas': 264,
 'lanjut': 1643,
 'lokasi': 1706,
 'zona': 3502,
 'lihat': 1685,
 'tselmeinternet': 3117,
 'gampang': 960,
 'chatting': 562,
 'bbm': 314,
 'whatsapp': 3272,
 'line': 1689,
 'harijika': 1093,
 'melanjutkantunggu': 1826,
 'pemakaianinfo': 2217,
 'tariff': 2942,
 'terima': 3003,
 'setting': 2733,
 'ponsel': 2335,
 'akses': 64,
 'fotomms': 915,
 'kali': 1414,
 'aktivasi': 68,
 'spasi': 2846,
 'kupon': 1614,
 'program': 2378,
 'as': 193,
 'biber': 381,
 'lengkap': 1672,
 'reguler': 2508,
 'kbdapatkan': 1454,
 'agam': 30,
 'layan': 1656,
 'voucher': 3237,
 'kenyang': 1489,
 'tukar': 3136,
 'poin': 2326,
 'menang': 1831,
 'hadih': 1069,
 'tinggi': 3040,
 'angpaopoinsenyum': 146,
 'vchr': 3222,
 'lottemart': 1711,
 'normal': 2059,
 'feb': 882,
 'wwwindosatooredoocomangpao': 3360,
 'ayam': 236,
 'sayappaha': 2641,
 'nasi': 1972,
 'perkedel': 2244,
 'teh': 2966,
 'pucuk': 2414,
 'cfc': 554,
 'hasan': 1101,
 'sadikin': 2603,
 'sedia': 2661,
 'ayo': 239,
 'anak': 106,
 'medan': 1815,
 'stiker': 2865,
 'klik': 1534,
 'nama': 1963,
 'stickernya': 2863,
 'dan': 638,
 'appleplay': 170,
 'store': 2867,
 'bronetjam': 460,
 'obor': 2103,
 'ld': 1659,
 'playapple': 2310,
 'dukung': 813,
 'lestari': 1675,
 'alam': 79,
 'indosat': 1216,
 'wwfindonesia': 3296,
 'donasi': 772,
 'nomor': 2044,
 'kawal': 1450,
 'manfaat': 1772,
 'subsidi': 2879,
 'kompensasi': 1566,
 'hak': 1076,
 'adu': 21,
 'banting': 282,
 'desember': 686,
 'ekspresi': 832,
 'diri': 740,
 'freedom': 919,
 'wwwindosatooredoocomfreedom': 3362,
 'internetas': 1261,
 'lychee': 1731,
 'tea': 2961,
 'latte': 1655,
 'flavour': 905,
 'yellow': 3478,
 'truck': 3112,
 'jlpatuha': 1360,
 'berlakupromo': 360,
 'gajah': 947,
 'wonderland': 3290,
 'bandung': 272,
 'tunjuk': 3145,
 'tugas': 3129,
 'wwwindosatcomkampunggajah': 3355,
 'donut': 773,
 'dunkin': 817,
 'donuts': 774,
 'borma': 435,
 'setiabudhi': 2730,
 'turbo': 3146,
 'aug': 222,
 'september': 2710,
 'tawar': 2948,
 'januari': 1327,
 'dapetkan': 644,
 'telepon': 2970,
 'april': 175,
 'ooredohanya': 2133,
 'jan': 1325,
 'menit': 1839,
 'bukti': 480,
 'argo': 183,
 'grabcar': 1035,
 'hayu': 1106,
 'rencang': 2519,
 'bareng': 290,
 'buktikeun': 481,
 'nyalira': 2091,
 'mycare': 1952,
 'dapat': 642,
 'freedoom': 920,
 'piknikada': 2258,
 'nih': 2026,
 'hongkongcarapake': 1150,
 'androidmu': 137,
 'banyak': 286,
 'items': 1296,
 'pokemon': 2328,
 'gobigococ': 1023,
 'dllinfo': 763,
 'buy': 502,
 'get': 1002,
 'trans': 3077,
 'studio': 2873,
 'bandungmulai': 274,
 'meijuni': 1823,
 'wwwindosatcomtransstudiobgd': 3356,
 'ramadhan': 2459,
 'hg': 1124,
 'pan': 2175,
 'operator': 2135,
 'komunikasi': 1569,
 'disc': 742,
 'mcdonalds': 1808,
 'tcash': 2954,
 'tapdptkan': 2938,
 'tap': 2937,
 'grapari': 1040,
 'dekat': 668,
 'tselmetappromo': 3119,
 'dominos': 771,
 'pizzaroti': 2299,
 'tebal': 2964,
 'keju': 1468,
 'pinggirmulai': 2278,
 'rpkunjungi': 2571,
 'toko': 3058,
 'terdekattelf': 3001,
 'panpizzacoid': 2182,
 'cappuccino': 519,
 'hotice': 1155,
 'freza': 922,
 'excelso': 866,
 'cafe': 508,
 'semarang': 2690,
 'yogya': 3481,
 'solo': 2835,
 'agust': 42,
 'wendys': 3271,
 'crispy': 613,
 'chicken': 564,
 'sandwich': 2629,
 'minimal': 1879,
 'main': 1751,
 'seninkamis': 2704,
 'timezone': 3037,
 'cipika': 575,
 'belanja': 333,
 'kuliner': 1603,
 'fashion': 874,
 'lain': 1630,
 'wwwindosatooredoocom': 3359,
 'dear': 663,
 'customer': 624,
 'kindly': 1518,
 'values': 3220,
 'your': 3482,
 'experience': 868,
 'at': 210,
 'score': 2648,
 'very': 3226,
 'poor': 2337,
 'excellent': 865,
 'free': 917,
 'intl': 1265,
 'charged': 557,
 'pizza': 2298,
 'value': 3219,
 'range': 2465,
 'agustuskunjungi': 44,
 'terdekathubungi': 3000,
 'visit': 3233,
 'kodevrd': 1554,
 'grab': 1034,
 'urangbandung': 3204,
 'repot': 2522,
 'jalan': 1317,
 'macet': 1739,
 'parkir': 2189,
 'ngegrab': 2006,
 'atuh': 216,
 'kacamata': 1400,
 'gatot': 971,
 'soebroto': 2826,
 'sampk': 2624,
 'pizzarotinya': 2300,
 'pinggir': 2277,
 'double': 778,
 'plus': 2318,
 'rasa': 2469,
 'seru': 2720,
 'gamegame': 954,
 'premium': 2359,
 'dptkn': 785,
 'card': 520,
 'larissa': 1653,
 'aesthetic': 25,
 'high': 1131,
 'treatment': 3085,
 'asuransi': 209,
 'jiwa': 1358,
 'galeri': 951,
 'jawa': 1335,
 'diy': 758,
 'sempat': 2696,
 'utama': 3216,
 'mobil': 1907,
 'alphard': 96,
 'senyum': 2707,
 'undi': 3180,
 'junketik': 1390,
 'rehabilitasi': 2509,
 'kembang': 1484,
 'potensi': 2346,
 'ypac': 3483,
 'jakarta': 1315,
 'mari': 1783,
 'bagi': 250,
 'etik': 860,
 'agt': 37,
 'datang': 649,
 'gallery': 952,
 'smartfrenmu': 2810,
 'andromax': 138,
 'mifi': 1866,
 'doublescoop': 779,
 'ice': 1185,
 'cream': 610,
 'haagendasz': 1060,
 'sim': 2765,
 'gerai': 999,
 'indosatooredoo': 1217,
 'jaring': 1331,
 'mana': 1767,
 'js': 1371,
 'masuk': 1793,
 'cobagrabcar': 587,
 'ajak': 55,
 'temantemanmu': 2981,
 'keliling': 1475,
 'tanp': 2935,
 'grabtaxi': 1036,
 'stasiunbandara': 2859,
 'grabtravel': 1037,
 'hatur': 1105,
 'nuhun': 2075,
 'token': 3057,
 'menu': 1844,
 'minimun': 1881,
 'rla': 2555,
 'hallo': 1078,
 'bro': 458,
 'koin': 1556,
 'games': 957,
 'yuk': 3495,
 'mudah': 1936,
 'banget': 276,
 'sob': 2825,
 'urang': 3203,
 'mang': 1773,
 'ado': 19,
 'rancak': 2462,
 'kampuang': 1423,
 'guy': 1057,
 'musik': 1950,
 'nelpsms': 1984,
 'sekrang': 2673,
 'tlb': 3050,
 'gbgbg': 976,
 'gbg': 974,
 'bronet': 459,
 'bronetspecial': 461,
 'jamgb': 1323,
 'special': 2847,
 'rabu': 2446,
 'blanja': 413,
 'blanjacom': 414,
 'bljcotcashrabu': 417,
 'senin': 2703,
 'nonton': 2051,
 'cema': 547,
 'xxi': 3449,
 'kunjung': 1607,
 'nrml': 2071,
 'lagistok': 1628,
 'terbatassd': 2998,
 'agtskinfodlj': 38,
 'mumpung': 1944,
 'ustad': 3214,
 'fatih': 876,
 'karimbeliau': 1435,
 'islam': 1290,
 'felix': 884,
 'siaw': 2752,
 'hi': 1128,
 'coba': 585,
 'mesan': 1852,
 'taxi': 2949,
 'aman': 99,
 'hot': 1153,
 'agsts': 36,
 'gbhr': 979,
 'juni': 1387,
 'spreading': 2851,
 'the': 3021,
 'gojek': 1024,
 'and': 109,
 'input': 1241,
 'this': 3024,
 'referral': 2501,
 'code': 591,
 'credit': 611,
 'first': 897,
 'booking': 434,
 'gojekgotmehere': 1025,
 'jobfairactive': 1363,
 'ujiklyakankerjaberstifikat': 3166,
 'plasatelkommlg': 2306,
 'platihan': 2308,
 'intrviewrekom': 1266,
 'kerja': 1498,
 'ph': 2255,
 'wwwindogetjobcom': 3352,
 'sumo': 2890,
 'tcashmu': 2955,
 'transfer': 3079,
 'bank': 279,
 'rekening': 2513,
 'hasil': 1102,
 'bimatri': 389,
 'rawit': 2478,
 'jumat': 1385,
 'ibadah': 1182,
 'haji': 1075,
 'nyaman': 2092,
 'lokalnikmati': 1705,
 'menithr': 1840,
 'trima': 3095,
 'indosatooredoointernet': 1219,
 'rprbhariinfo': 2577,
 'pai': 2163,
 'kejar': 1467,
 'lari': 1652,
 'sendiriayo': 2702,
 'sekarangdan': 2671,
 'pasti': 2201,
 'besok': 365,
 'rawitinfold': 2479,
 'lupa': 1727,
 'sesame': 2725,
 'prog': 2377,
 'us': 3208,
 'kalah': 1409,
 'mu': 1933,
 'baskin': 296,
 'robbins': 2558,
 'scoop': 2647,
 'lho': 1680,
 'infold': 1227,
 'rbnrml': 2487,
 'glte': 1017,
 'gbkonten': 981,
 'tarik': 2944,
 'wwwindosatooredoocomg': 3363,
 'langka': 1641,
 'tld': 3052,
 'flashspasiinfo': 901,
 'status': 2860,
 'loopers': 1710,
 'tren': 3086,
 'muda': 1935,
 'challenge': 555,
 'loopcoid': 1709,
 'followloop': 907,
 'id': 1186,
 'maret': 1782,
 'perbln': 2236,
 'lgs': 1679,
 'gbgbonus': 977,
 'doyan': 782,
 'slm': 2800,
 'oke': 2118,
 'pnwrn': 2325,
 'kocak': 1551,
 'aksi': 65,
 'pemuda': 2224,
 'galau': 949,
 'iseng': 1285,
 'gokil': 1027,
 'kepung': 1493,
 'polisi': 2331,
 'super': 2895,
 'cantik': 515,
 'tonton': 3063,
 'komik': 1563,
 'film': 892,
 'tinggal': 3039,
 'lanjutin': 1644,
 'gamesmu': 958,
 'data': 647,
 'kuotaspasik': 1613,
 'lets': 1676,
 'rich': 2547,
 'google': 1030,
 'play': 2309,
 'pakettelkomselflash': 2171,
 'gbberlaku': 973,
 'otomatis': 2148,
 'pd': 2206,
 'maaf': 1734,
 'milik': 1870,
 'timur': 3038,
 'lombok': 1707,
 'appsinapps': 174,
 'dki': 760,
 'nsp': 2072,
 'keren': 1495,
 'internetmu': 1262,
 'gift': 1007,
 'paketextra': 2170,
 'smuanya': 2819,
 'file': 890,
 'putus': 2440,
 'gatis': 970,
 'mifimodem': 1867,
 'untuk': 3193,
 'bawa': 304,
 'sf': 2734,
 'sana': 2627,
 'surveu': 2901,
 'singkat': 2776,
 'murah': 1946,
 'juli': 1384,
 'jajan': 1313,
 'online': 2129,
 'suka': 2883,
 'nge': 1999,
 'jul': 1383,
 'pergi': 2238,
 'aliando': 92,
 'merdeka': 1848,
 'sale': 2617,
 'harirprb': 1096,
 'migrasi': 1868,
 'kartuhalo': 1439,
 'rbbulan': 2482,
 'inipromo': 1238,
 'terbatasskb': 2999,
 'ributrip': 2545,
 'nasabah': 1970,
 'btpn': 467,
 'wow': 3292,
 'pin': 2262,
 'rahasia': 2451,
 'mall': 1764,
 'sin': 2771,
 'thailand': 3019,
 'hk': 1144,
 'china': 565,
 'usa': 3209,
 'negarano': 1981,
 'wwwindosatooredoocomflatcall': 3361,
 'fried': 923,
 'minum': 1886,
 'junitukarkan': 1389,
 'terbataspromo': 2997,
 'big': 384,
 'pesta': 2254,
 'weekendharga': 3269,
 'rprbberlaku': 2575,
 'dine': 733,
 'intake': 1254,
 'away': 229,
 'maykunjungi': 1799,
 'bakmi': 260,
 'gm': 1018,
 'sli': 2797,
 'negara': 1980,
 'wib': 3273,
 'wwwindosatcomiddpromo': 3354,
 'chn': 567,
 'mlahkgsngtwnvtmmacau': 1892,
 'kuat': 1599,
 'tlpsms': 3053,
 'indosatooredoocomfreedom': 1218,
 'agst': 35,
 'visa': 3231,
 'midnight': 1863,
 'ckp': 578,
 'rbminggu': 2486,
 'mbmbbonus': 1806,
 'hggmbpstekan': 1125,
 'syarat': 2910,
 'iur': 1298,
 'bpjs': 439,
 'twallet': 3149,
 'smartphone': 2811,
 'iphone': 1276,
 'mini': 1878,
 'sn': 2820,
 'netmax': 1987,
 'situs': 2785,
 'tricoid': 3093,
 'untung': 3194,
 'tes': 3011,
 'identitas': 1188,
 'vd': 3223,
 'handphone': 1080,
 'myxlcoid': 1957,
 'restart': 2532,
 'skema': 2790,
 'wwwtelkomselcom': 3423,
 'non': 2046,
 'kebut': 1460,
 'pcs': 2205,
 'strip': 2870,
 'sayapnasiteh': 2640,
 'rptukarkan': 2581,
 'subang': 2877,
 'iniselama': 1239,
 'adapromo': 12,
 'mar': 1778,
 'ubah': 3157,
 'off': 2108,
 'update': 3196,
 'tselmeas': 3115,
 'daves': 651,
 'single': 2777,
 'burger': 495,
 'small': 2807,
 'fries': 924,
 'obral': 2104,
 'gbnelpon': 982,
 'minggudaftar': 1877,
 'rtx': 2586,
 'ythmohon': 3488,
 'nilai': 2031,
 'type': 3152,
 'english': 846,
 'sdnov': 2653,
 'dlk': 762,
 'tselpoin': 3121,
 'facebook': 871,
 'video': 3228,
 'quota': 2444,
 'merchant': 1846,
 'voice': 3234,
 'ri': 2541,
 'ags': 34,
 'miring': 1887,
 'bolak': 430,
 'pulsacek': 2423,
 'rprbbln': 2576,
 'gbggb': 978,
 'gmau': 1020,
 'gbgb': 975,
 'pindah': 2273,
 'jljend': 1359,
 'soedirmanpurwokerto': 2827,
 'bns': 424,
 'selamat': 2674,
 'berrybenka': 362,
 'twd': 3150,
 'wwwberrybenkacomsimpati': 3305,
 'lazada': 1658,
 'tst': 3123,
 'wwwlazadacoidsimpati': 3392,
 'zalora': 3499,
 'tsu': 3124,
 'wwwzaloracoidsimpati': 3440,
 'gabung': 937,
 'harikuota': 1094,
 'lipat': 1691,
 'aktivitas': 69,
 'statusberhenti': 2861,
 'pas': 2191,
 'instink': 1251,
 'cs': 614,
 'selamatanda': 2675,
 'smsgift': 2815,
 'sensasi': 2705,
 'game': 953,
 'heroes': 1122,
 'hit': 1138,
 'ball': 266,
 'pool': 2336,
 'gmmu': 1021,
 'limpah': 1688,
 'luculucu': 1719,
 'ckup': 579,
 'akumulasi': 71,
 'tlc': 3051,
 'mataharimall': 1795,
 'sahabat': 2608,
 'kenal': 1486,
 'yaok': 3474,
 'heboh': 1113,
 'artisartis': 188,
 'top': 3064,
 'menittlp': 1841,
 'menitvideo': 1842,
 'yesok': 3479,
 'kini': 1519,
 'ungkapin': 3184,
 'pikir': 2257,
 'stickershop': 2864,
 'aneka': 139,
 'merchants': 1847,
 'partner': 2190,
 'thank': 3020,
 'appreciation': 172,
 'in': 1205,
 'using': 3213,
 'further': 930,
 'feedback': 883,
 'mohon': 1917,
 'nasehat': 1971,
 'freefor': 921,
 'tingkat': 3041,
 'rpribu': 2579,
 'pernuh': 2246,
 'dapet': 643,
 'trmksh': 3104,
 'jual': 1377,
 'pulsabayar': 2422,
 'listrikspeedytelkom': 1695,
 'hubagen': 1166,
 'barokahmp': 291,
 'reloadpasti': 2515,
 'up': 3195,
 'coins': 592,
 'themes': 3022,
 'koleksi': 1559,
 'use': 3212,
 'nxmvfue': 2085,
 'ride': 2548,
 'redeem': 2499,
 'penuh': 2232,
 'batasankami': 299,
 'kebebasa': 1458,
 'kuotacuma': 1612,
 'dengerin': 675,
 'seleb': 2681,
 'blog': 419,
 'suara': 2876,
 'rpmggcs': 2572,
 'vas': 3221,
 'twitter': 3151,
 'temen': 2984,
 'bioskop': 393,
 'cigna': 571,
 'bitlytentangcigna': 406,
 'yuks': 3496,
 'seruseruan': 2721,
 'resmi': 2529,
 'tunai': 3141,
 'jt': 1372,
 'gebyar': 985,
 'nasional': 1977,
 'klaim': 1530,
 'xxxxxx': 3453,
 'akun': 72,
 'mbanking': 1803,
 'silah': 2763,
 'verifikasi': 3224,
 'bitlybcalogin': 402,
 'tahan': 2922,
 'gudang': 1050,
 'alamat': 80,
 'resi': 2524,
 'admin': 16,
 'sidcekpaket': 2756,
 'langgar': 1640,
 'sistem': 2783,
 'otp': 2149,
 'hindar': 1136,
 'blokir': 421,
 'sosial': 2840,
 'bantuanresmimyid': 284,
 'danaid': 640,
 'login': 1701,
 'perangkat': 2235,
 'bitlydanaverif': 403,
 'uang': 3153,
 'hadiahpoincom': 1066,
 'unit': 3186,
 'pro': 2372,
 'acara': 8,
 'pusat': 2432,
 'pajak': 2164,
 'kendara': 1488,
 'bb': 311,
 'xx': 3448,
 'tunggak': 3142,
 'denda': 673,
 'taut': 2947,
 'shopeepay': 2745,
 'bitlyshopeelogin': 405,
 'permanen': 2245,
 'nik': 2027,
 'kk': 1527,
 'registrasionlinemyid': 2506,
 'avanza': 225,
 'administrasi': 17,
 'juta': 1393,
 'mobile': 1908,
 'banking': 281,
 'tinyurlcomverifikasimbank': 3042,
 'ovoid': 2155,
 'ilegal': 1199,
 'plnpusat': 2316,
 'beku': 331,
 'jneinfo': 1362,
 'kurang': 1616,
 'selesai': 2683,
 'mandiricare': 1771,
 'proses': 2386,
 'rpjt': 2565,
 'cair': 510,
 'cckt': 535,
 'stres': 2869,
 'bunga': 493,
 'lunas': 1726,
 'aty': 220,
 'wa': 3239,
 'legal': 1666,
 'lelah': 1668,
 'payment': 2203,
 'solusi': 2836,
 'cckta': 536,
 'dscn': 801,
 'hublolyta': 1173,
 'dana': 639,
 'ktp': 1593,
 'cc': 533,
 'bcainfo': 317,
 'mbca': 1804,
 'curiga': 622,
 'bitlyloginbcaid': 404,
 'bpkb': 440,
 'rate': 2473,
 'ayu': 241,
 'wamhn': 3253,
 'menggangu': 1836,
 'roxi': 2564,
 'cell': 545,
 'agen': 31,
 'elektrik': 835,
 'gsmcdmavvutk': 1047,
 'mtronik': 1931,
 'yrkz': 3484,
 'wwwhadiahramadhanblogspotcom': 3343,
 'brminat': 455,
 'cashkredit': 530,
 'motor': 1920,
 'scond': 2646,
 'istmwa': 1293,
 'tipemerk': 3043,
 'sjdsini': 2786,
 'mnyediakn': 1903,
 'atas': 211,
 'ms': 1926,
 'dediktp': 665,
 'yk': 3480,
 'togel': 3056,
 'tembus': 2983,
 'shio': 2741,
 'tunggal': 3143,
 'angka': 144,
 'mahar': 1747,
 'xxx': 3450,
 'sgp': 2735,
 ...}

In [39]:
len(new_selection_feature)

3000

In [40]:
pickle.dump(new_selection_feature,open("new_selected_feature_tf-idf.sav","wb"))

In [41]:
# menampilkan fitur-fitur yang sudah diseleksi

data_selected_feature = pd.DataFrame(x_kbest_features, columns=selected_feature)
data_selected_feature

,aa,aamiiiin,aamiin,ab,abadi,abai,abbee,abdul,acara,acaratks,...,yudisium,yuk,yuks,yuni,yunit,zalora,zarkasi,zjt,zona,ztkm
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1191,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1192,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1193,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1194,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1195,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

## Modeling

In [42]:
selected_x = x_kbest_features
selected_x

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], shape=(1196, 3000))

In [43]:
# import library
import random
from sklearn.model_selection import train_test_split

#import algoritma naive bayes
from sklearn.naive_bayes import MultinomialNB

In [44]:
x = selected_x
y = data.label

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)

In [45]:
# menampilkan jumlah data training dan data testing
print('Banyaknya X_train : ', len(x_train))
print('Banyaknya X_test : ', len(x_test))
print('Banyaknya Y_train : ', len(y_train))
print('Banyaknya Y_test : ', len(y_test))

Banyaknya X_train :  956
Banyaknya X_test :  240
Banyaknya Y_train :  956
Banyaknya Y_test :  240

In [46]:
# prosess training menggunakan naive bayes
text_algorthm = MultinomialNB()

In [47]:
model = text_algorthm.fit(x_train, y_train)

In [48]:
# membuat model prediksi

data_input =("tolong belikan nama pulsa nomor as  nama teman mama celaka keluarganya hubung mama ganti uangnyapenting")
data_input = text_preprocessing_process(data_input)

# load
tfidf = TfidfVectorizer

loaded_vec = TfidfVectorizer(decode_error="replace", vocabulary=set(pickle.load(open("new_selected_feature_tf-idf.sav", "rb"))))

hasil = model.predict(loaded_vec.fit_transform([data_input]))

if(hasil==0):
    s = "SMS Normal"
elif(hasil==1):
    s = "SMS Fraud"
else:
    s = "SMS Promo"

print("Hasil Prediksi : \n", s)

Hasil Prediksi :
 SMS Fraud

## Evaluasi Model

In [49]:
# masukan library yg dibutuhkan
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

predicted = model.predict(x_test)

CM = confusion_matrix(y_test, predicted)

print(classification_report(y_test, predicted))

              precision    recall  f1-score   support

           0       0.96      0.96      0.96       120
           1       0.91      0.89      0.90        76
           2       0.87      0.89      0.88        44

    accuracy                           0.93       240
   macro avg       0.91      0.91      0.91       240
weighted avg       0.93      0.93      0.93       240

In [50]:
pickle.dump(model,open("model_fraud.sav", "wb"))